### PR TITLE
Adds refresh button to fix list & export errors

### LINKED ISSUE #157: Saved lists count and exports do not include all selected entries
Screen Shot 2019-07-25 at 5 07 50 AM

Screen Shot 2019-07-25 at 5 08 14 AM

### LINKED ISSUE #181: weird export issue
when i am in this saved list, and select all and then export, the export covers only 6 of the 8 entries, leaving out charles hope and stephenson. NOTE that i'm encountering this issue in the live explorer not in alpha

### LINKED ISSUE #188: duplicate list total number errros
I opened a saved list, it showed to have 50 entries which is correct (Paul); i duplicated it and renamed it (Paul all) and this new list shows 49 total entries which is incorrect (the total is as it should
Screen Shot 2019-09-06 at 10 00 16 AM
 be fifty entries)

### PR DESCRIPTION
**Pull request by ryanctan**
Fixes #157, fixes #181, fixes #188.

Not the most ideal solution, but given the time constraints and the severity of these long-discovered issues, it seemed like the simplest way to deal with the problem.

### CODE REVIEW

**Comment by epicfaace** [comment]
Hmmm, this seems equivalent to just a notice asking the user to refresh the browser. As the user is never certain that the current list will be correct, they will end up _always_ clicking the refresh button the first time they load the page...

**Comment by epicfaace** [comment]
If we can create reproducible steps for each list issue, they will be easier to track down and debug.

**Comment by ryanctan** [comment]
@epicfaace #157 appears relatively consistently, if you query in Explore (say select all 165 painters) and add to a list, Saved Lists reports the number to be under 165 (in my recent test 161), those missing fail to export, but they are all listed in the right column. Issues are fixed when refreshing the page.

#181 and #188 are harder to reproduce and I have not encountered them in my testing.

**Comment by ryanctan** [comment]
Closed in favor of #225

**Pull request closed without merging**
