### PR TITLE
Allow access by anonymous users

### PR DESCRIPTION
**Pull request by epicfaace**
Users who are not logged in can:
- Search for entries
- Explore
- View visualizations

They cannot:
- Export to CSV
- Save / Edit Saved Lists

### CODE REVIEW

**Comment by ceserani** [comment]
one addendum:
we are allowing readers to see the lists that will come with the book, which are the list relevant tot he essays. there are seven of them. and i imagine also that it would be good if when reader A (with an account) sends reader B a list s/he made, reader B can look it up in the Explorer, but only save it or any modifications to it if s/he makes an account. how will this work?

the above is to encourage as much as possible use of the explorer and perusal of the lists relevant to essays one will read in the book so as to inspire making an account.

we should have administrator and editor profiles still too , right?

**Review by ryanctan — CHANGES_REQUESTED** [review]
Awesome! Few things I noticed:
- Even while logged out, the Add to List feature appears on an entry's page
- Even while logged out, I can replace the hash to "/lists" and access lists, but refreshing the page fixes it. Same with the reverse: if I then log in my lists are gone unless I refresh.
- Even while logged in, I can't Add selected entries to list or export from either Explore tab or Lists

**Comment by epicfaace** [comment]
@ryanctan I've fixed the first and third issues. I don't see what you mean by the second issue; I can't reproduce it. Can you give more details on that one?

We will also eventually probably want non-logged-in users to be able to view any lists by link, but they just can't edit or create any lists.

**Review by ryanctan — APPROVED** [review]
The second change was about a non-logged-in user potentially changing the url to have /list at the end but this is probably rare and also likely unnecessary to check for given the info about anonymous access to lists. Looks great!

**Pull request merged**
